package com.musicfly.backend.models;

/**
 * Este enum representa los diferentes géneros musicales disponibles en el sistema.
 * Los géneros van desde los más populares como Hip-Hop, Rock y Pop, hasta géneros más específicos
 * como Reggaeton, EDM y K-Pop. Los valores de este enum son utilizados para categorizar las canciones
 * y otros elementos dentro de la aplicación, garantizando consistencia y un acceso más fácil a los géneros.
 */
public enum GenreType {
    HIP_HOP,
    RAP,
    TRAP,
    RNB,
    POP,
    ROCK,
    ALTERNATIVE_ROCK,
    HARD_ROCK,
    PUNK_ROCK,
    METAL,
    HEAVY_METAL,
    THRASH_METAL,
    INDIE,
    INDIE_ROCK,
    INDIE_POP,
    ELECTRONIC,
    EDM,
    HOUSE,
    TECHNO,
    TRANCE,
    DUBSTEP,
    DRUM_AND_BASS,
    JAZZ,
    BLUES,
    FUNK,
    SOUL,
    CLASSICAL,
    REGGAE,
    REGGAETON,
    SALSA,
    BACHATA,
    CUMBIA,
    FLAMENCO,
    FOLK,
    COUNTRY,
    LATIN,
    AFROBEAT,
    K_POP,
    J_POP,
    LOFI,
    AMBIENT,
    EXPERIMENTAL,
    INSTRUMENTAL,
    ACOUSTIC,
    SOUNDTRACK,
    GOSPEL,
    OPERA,
    DANCEHALL,
    DISCO,
    GRIME,
    DRILL,
    PHONK,
    CHILLWAVE,
    SYNTHWAVE,
    NEW_WAVE
}
